services:
  gomoku-webapp:
    image: gomoku-webapp
    build:
      context: .
      dockerfile: Gomoku-WebApp/Dockerfile
  gamedb:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "gamedb"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=someThingComplicated1234